define([], function() {
  return {
    "WelcomeWebpartText": "Welcome to SharePoint!",
    "WelcomeDescriptionText": "This is a Webpart with Graph conection. Check webpart's properties!",
    "PropertyPaneDescription": "Webpart configuration",
    "BasicGroupName": "Graph data types",
    "DescriptionFieldLabel": "Description Field",
    "GraphDataOptionsLabel": "Select type of data to retreive from Graph",
    "NoDataOptionSelected": "There's no data option selected",
    "CannotLoadUserData": "Cannot load current user data",
    "YourEmailIs": "Your email is",
    "Hi": "Hi",
    "NotDefinedUserEmail": "There's no defined email in user information",
    "GetMyUserData": "Get my user data",
    "GetMyMails": "Get my mails",
    "GetMyTeams": "Get my teams",
    "GetMyEvents": "Get my events",
    "NotSupportedOption": "Not supported option",
    "HaveNotEmails": "You have not emails.",
    "HaveNotTeams": "You have not teams.",
    "HaveNotEvents": "You have not events.",
    "CannotLoadUserMails": "Cannot load user emails",
    "CannotLoadUserEvents": "Cannot load user events",
    "CannotLoadUserTeams": "Cannot load user teams",
    "Received": "Received",
    "From": "From",
    "Subject": "Subject",
    "TeamName": "Team Name",
    "TeamDescription": "Team Description",
    "Organizer": "Organizer",
    "Start": "Start",
    "End": "End",
    "Location": "Location",
    "Read": "Read",
    "Yes": "Yes",
    "No": "No",
    "TeamChannels": "Channels"
  }
});