define([], function() {
  return {
    "WelcomeWebpartText": "¡Bienvenida a SharePoint!",
    "WelcomeDescriptionText": "Este es un webpart con conexión con Graph. ¡Configura las propiedades del webpart!",
    "PropertyPaneDescription": "Configuración del webpart",
    "BasicGroupName": "Tipos de datos de Graph",
    "DescriptionFieldLabel": "Descripción",
    "GraphDataOptionsLabel": "Selecciona un tipo de dato para obtener de Graph",
    "NoDataOptionSelected": "No hay una opción de datos elegida todavía",
    "CannotLoadUserData": "No se han podido cargar los datos del usuario",
    "YourEmailIs": "Tu email es",
    "Hi": "Hola",
    "NotDefinedUserEmail": "No tienes email definido en tu información de usuario",
    "GetMyUserData": "Obtener mis datos de usuario",
    "NotSupportedOption": "Opción no soportada",
    "GetMyMails": "Obtener mis emails",
    "GetMyTeams": "Obtener mis teams",
    "GetMyEvents": "Obtener mis eventos",
    "HaveNotEmails": "No tienes emails.",
    "HaveNotTeams": "No tienes teams.",
    "HaveNotEvents": "No tienes eventos.",
    "CannotLoadUserMails": "No se han podido cargar los emails del usuario",
    "CannotLoadUserEvents": "No se han podido cargar los eventos del usuario",
    "CannotLoadUserTeams": "No se han podido cargar los teams del usuario",
    "Received": "Receptor",
    "From": "Remitente",
    "Subject": "Asunto",
    "TeamName": "Nombre del equipo",
    "TeamDescription": "Descripción del equipo",
    "Organizer": "Organizador",
    "Start": "Inicio",
    "End": "Fin",
    "Location": "Ubicación",
    "Read": "Leído",
    "Yes": "Sí",
    "No": "No"
  }
});